#:schema node_modules/wrangler/config-schema.json
name = "sdzl-xget"
main = "src/index.js"
compatibility_date = "2025-08-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

routes = [
  "sdzl-xget.aphd.cn/*",
  "*.sdzl-xget.hxorz.cn/*",
]

[observability]
enabled = true
head_sampling_rate = 1
